### PR TITLE
Eulerlagrange/erc1271-sigs

### PR DESCRIPTION
**Pull request by Hmac512**
## Motivation

This PR adds support for verifying signatures of smart contract wallets, and EOA's.

Related to this issue.

https://github.com/farcasterxyz/hub-monorepo/issues/1035

This PR still needs some cleanup and full coverage tests, but there are open questions related to the hub that need to be resolved before contract updates can be made. See the discussion in the linked issue.

## Change Summary

1. Change the _verifyRegisterSig and _verifyTransferSig to use the SignatureChecker from openzeppelin.
2. Add mock smart contract wallet to help with tests.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] The PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] The PR has been tagged with change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] The PR's changes adhere to all the requirements in the [contribution guidelines](https://github.com/farcasterxyz/contracts/blob/main/CONTRIBUTING.md#3-proposing-changes)
- [ ] This PR does not require changes to the [Farcaster protocol](https://github.com/farcasterxyz/protocol)

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers.

---

### Detailed summary
- Added `_signMsg` function to `IdRegistryTestSuite.sol` to generate signatures for testing purposes.
- Imported `SignatureChecker` in `IdRegistry.sol` and used it for signature verification in `_verifyRegisterSig` and `_verifyTransferSig` functions.
- Added view functions `verifyfIdOwner` and `verifyfIdOwnerSignature` in `IdRegistry.sol` to verify ownership of fIds and their corresponding signatures.
- Added tests in `IdRegistryTest.t.sol` to test the new signature verification functions.

> The following files were skipped due to too many changes: `test/IdRegistry/IdRegistry.t.sol`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by varunsrin** [comment]
Thanks for the PR @Hmac512! 

This PR makes sense to me directionally, but before we get into cleaning this up I want to understand the concerns in the Hubs which don't quite make sense to me yet. Left some comments in the linked discussion.

**Comment by horsefacts** [comment]
Thanks for this, @Hmac512! We should definitely support 1271 for fid transfers and key registration, even if hubs don't use 1271 sigs. I pulled some of this into #286 and added you to the commit as a co-author.

**Comment by Hmac512** [comment]
> Thanks for this, @Hmac512! We should definitely support 1271 for fid transfers and key registration, even if hubs don't use 1271 sigs. I pulled some of this into #286 and added you to the commit as a co-author.

Thanks for adding me to the PR. Sorry for leaving this PR in a messy state, was waiting for some direction from Varun before cleaning it up. Even happier now that I don't have to go through the trouble.

Probably want to indicate the progress in this issue: https://github.com/farcasterxyz/hub-monorepo/issues/1035

**Comment by horsefacts** [comment]
Left a comment on that thread, thanks @Hmac512. Gonna close this one—thank you for bringing it up!

**Pull request closed without merging**
