### PR TITLE
perf: remove payable wherever its not needed

### PR DESCRIPTION
**Pull request by jaglinux**
Fixes https://github.com/farcasterxyz/contracts/issues/129 
Removing payable will increase gas but will prevent users accidentally sending ether.

Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

## Motivation

Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.

## Change Summary

Describe the changes being made in 1-2 concise sentences.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] The PR has been tagged with change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] The PR's changes adhere to all the requirements in the [contribution guidelines](https://github.com/farcasterxyz/contracts/blob/main/CONTRIBUTING.md#3-proposing-changes)
- [x] This PR does not require changes to the [Farcaster protocol](https://github.com/farcasterxyz/protocol)

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers.

### CODE REVIEW

**Comment by jaglinux** [comment]
@varunsrin plz review.

**Comment by jaglinux** [comment]
The tests which are failing in CI are passing locally.
forge test -vvv | grep testCannotGetTokenUriForInvalidName
[PASS] testCannotGetTokenUriForInvalidName() (gas: 15371)
forge test -vvv | grep testSafeTransferFromOwner          
[PASS] testSafeTransferFromOwner(address,address,address) (runs: 512, μ: 238304, ~: 238256)

**Comment by varunsrin** [comment]
tests seem to be failing consistently in CI, while they are passing in other actions like [this one](https://github.com/farcasterxyz/contracts/actions/runs/3708504261).

can you look into why that's happening?

also, you'll need to sign your commits

**Comment by jaglinux** [comment]
@varunsrin signed commits.
Can you re trigger CI run, I will debug if it fails again.

**Comment by varunsrin** [comment]
@jaglinux try rebasing off my latest changes, i fixed some false positive fuzzer failures

**Comment by jaglinux** [comment]
@varunsrin done, looks like CI needs approval.

**Comment by varunsrin** [comment]
ci failed since the gas usage increased. also commits need to be signed to be merged.

**Comment by jaglinux** [comment]
@varunsrin its signed with gpg now.

**Comment by varunsrin** [comment]
its not yet correctly signed, and the snapshot shouldnt be run over all the methods, just the gas related ones

**Comment by jaglinux** [comment]
The first commit on Dec 12 is not signed. I guess need to submit new PR

**Pull request closed without merging**
