### PR TITLE
Slither CI workflow

### PR DESCRIPTION
**Pull request by GarrettJMU**
## Motivation

Coming from issue:
https://github.com/farcasterxyz/contracts/issues/70

## Change Summary

Add slither to the ci workflow

## Merge Checklist
- [x] The PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] The PR has been tagged with change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] The PR's changes adhere to all the requirements in the [contribution guidelines](https://github.com/farcasterxyz/contracts/blob/main/CONTRIBUTING.md#3-proposing-changes)
- [x] This PR does not require changes to the [Farcaster protocol](https://github.com/farcasterxyz/protocol)

## Additional Context
n/a

### CODE REVIEW

**Comment by varunsrin** [comment]
Thanks for making this PR. 

Unfortunately, this seems to fail because slither is taking > 10 minutes to run. I don't think its a good idea to have such an expensive test suite run on every commit to a branch. I'm going to explore some options for speeding this up, open to suggestions if you have any

**Comment by GarrettJMU** [comment]
@varunsrin - Hm - I think a few other things. It doesn't look like we're not omitting node_modules but maybe taking a step back, what do you want to test here? 

Do we also need to test all the folders in lib? Seems like right now we are just omitting forge-std. I just pushed an update to omit lib altogether and might be interesting to see what time tradeoff that has.

**Comment by varunsrin** [comment]
Yeah, i made another PR where I got it down to 11 minutes, but that's still painfully slow for every PR. Appreciate your work on this but it might not make sense to merge right now given how slow it is and just do the checks manually before contract releases.

**Comment by varunsrin** [comment]
closing for now since we're not moving forward, thanks for trying @GarrettJMU

**Pull request closed without merging**
